@startuml
!include ./Camera.puml
!include ./Render.puml
!include ./Scene.puml

class BaseThreeJSWrapper {
    #camera: Camera
    #renderer: Renderer
    #scene: SceneWrapper
    #controller: OrbitControls

    + constructor(domElement: HTMLElement)
    + init(): void
    + animate(): void
    + modifyTheCameraPosition(x: number, y: number, z: number): void
    + initializeTheController(): void
    + setUpTheDHRMap({url:string}): void
    + enableStatusDisplay(): void
    + windowChangeExecution(): void

}

Camera -[dashed]-> BaseThreeJSWrapper :[引用]
Render -[dashed]-> BaseThreeJSWrapper :[引用]
Scene -[dashed]-> BaseThreeJSWrapper :[引用]

note left of BaseThreeJSWrapper::init
    初始化相机、渲染器、场景
end note
note left of BaseThreeJSWrapper::animate
    动画,果启动了轨道控制器,则需要在此处更新
end note
note right of BaseThreeJSWrapper::modifyTheCameraPosition
    修改相机位置
end note
note left of BaseThreeJSWrapper::initializeTheController
    初始化控制器
end note
note left of BaseThreeJSWrapper::setUpTheDHRMap
    HDR贴图设置,如果不设置则使用默认的贴
end note
@enduml
