@startuml
class Camera {
    + instance:Camera
    + constructor(type:0|1)
    + getCamera():Camera
}
note right of Camera::instance
    相机实例
end note

note right of Camera::getCamera
    获取相机实例
end note

@enduml
